repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
        -   id: detect-private-key
        -   id: check-case-conflict
  -   repo: https://github.com/gitleaks/gitleaks
      rev: v8.18.4
      hooks:
        - id: gitleaks
  -   repo: https://github.com/imajacket/pre-commit-golang
      rev: ecbd91e63af100a52c118190ff09410b354a59fe
      hooks:
        -   id: go-fmt
        -   id: go-vet
        -   id: go-imports
        -   id: go-cyclo
        -   id: go-critic
        #    -   id: go-unit-tests
        -   id: go-mod-tidy
        -   id: go-betteralign
